import React, { useState, useEffect } from 'react';
import { Trainee, DietPlan, Meal, FoodItem, FoodPortion, DaySchedule } from '../types/nutrition';
import { autoGenerateDietPlan } from '../utils/dietGenerator';
import { computeTraineeNutritionStats } from '../utils/calculator';
import { 
  Sparkles, 
  Dumbbell, 
  Plus, 
  Trash2, 
  RefreshCw, 
  FileText, 
  Calendar,
  Copy,
  Scale,
  Flame,
  Check
} from 'lucide-react';

interface DietGeneratorViewProps {
  trainees: Trainee[];
  selectedTraineeId: string;
  onSelectTraineeId: (id: string) => void;
  foodDatabase: FoodItem[];
  currentPlan?: DietPlan;
  onSavePlan: (plan: DietPlan) => void;
  onGoToPdf: () => void;
}

export const DietGeneratorView: React.FC<DietGeneratorViewProps> = ({
  trainees,
  selectedTraineeId,
  onSelectTraineeId,
  foodDatabase,
  currentPlan,
  onSavePlan,
  onGoToPdf
}) => {
  const selectedTrainee = trainees.find(t => t.id === selectedTraineeId) || trainees[0];
  const [activePlan, setActivePlan] = useState<DietPlan | null>(null);
  
  // Selected active day index (0: Saturday to 6: Friday)
  const [activeDayIndex, setActiveDayIndex] = useState<number>(0);
  const [copiedNotification, setCopiedNotification] = useState(false);

  // Food selection state
  const [selectedFoodIdToAdd, setSelectedFoodIdToAdd] = useState<string>('');
  const [newMealTitle, setNewMealTitle] = useState('');
  const [showAddMealModal, setShowAddMealModal] = useState(false);

  const traineeStats = selectedTrainee ? computeTraineeNutritionStats(selectedTrainee) : null;

  useEffect(() => {
    if (selectedTrainee) {
      if (currentPlan && currentPlan.traineeId === selectedTrainee.id) {
        setActivePlan(currentPlan);
      } else {
        const generated = autoGenerateDietPlan(selectedTrainee, foodDatabase);
        setActivePlan(generated);
      }
    }
  }, [selectedTraineeId]);

  const daysNames = [
    { ar: 'السبت', en: 'Saturday' },
    { ar: 'الأحد', en: 'Sunday' },
    { ar: 'الإثنين', en: 'Monday' },
    { ar: 'الثلاثاء', en: 'Tuesday' },
    { ar: 'الأربعاء', en: 'Wednesday' },
    { ar: 'الخميس', en: 'Thursday' },
    { ar: 'الجمعة', en: 'Friday' }
  ];

  // Current active day schedule
  const activeDaySchedule: DaySchedule | undefined = activePlan?.days ? activePlan.days[activeDayIndex] : undefined;
  const currentMeals: Meal[] = activeDaySchedule?.meals || activePlan?.meals || [];

  // Copy current day's 5 meals to all 7 days of the week
  const handleCopyCurrentDayToAllDays = () => {
    if (!activePlan || !activePlan.days) return;

    const currentMealsCopy = JSON.parse(JSON.stringify(currentMeals));

    const updatedDays: DaySchedule[] = activePlan.days.map((day, idx) => ({
      ...day,
      meals: currentMealsCopy.map((m: Meal) => ({ ...m, id: `m-${idx}-${Date.now()}-${m.id}` }))
    }));

    const updatedPlan = {
      ...activePlan,
      days: updatedDays,
      meals: currentMealsCopy
    };

    setActivePlan(updatedPlan);
    onSavePlan(updatedPlan);
    setCopiedNotification(true);
    setTimeout(() => setCopiedNotification(false), 3000);
  };

  const handleStartBlankPlan = () => {
    if (!selectedTrainee || !traineeStats) return;

    const days: DaySchedule[] = daysNames.map((d, idx) => ({
      dayIndex: idx,
      dayNameAr: d.ar,
      dayNameEn: d.en,
      meals: [
        { id: `blank-1-${idx}`, type: 'breakfast', titleAr: '1. وجبة الإفطار', titleEn: 'Breakfast', items: [], totalCalories: 0, totalProtein: 0, totalCarbs: 0, totalFats: 0 },
        { id: `blank-2-${idx}`, type: 'snack_1', titleAr: '2. وجبة سناك صباحي', titleEn: 'Morning Snack', items: [], totalCalories: 0, totalProtein: 0, totalCarbs: 0, totalFats: 0 },
        { id: `blank-3-${idx}`, type: 'lunch', titleAr: '3. وجبة الغداء الرئيسية', titleEn: 'Lunch', items: [], totalCalories: 0, totalProtein: 0, totalCarbs: 0, totalFats: 0 },
        { id: `blank-4-${idx}`, type: 'post_workout', titleAr: '4. وجبة قبل/بعد التمرين', titleEn: 'Workout Meal', items: [], totalCalories: 0, totalProtein: 0, totalCarbs: 0, totalFats: 0 },
        { id: `blank-5-${idx}`, type: 'dinner', titleAr: '5. وجبة العشاء', titleEn: 'Dinner', items: [], totalCalories: 0, totalProtein: 0, totalCarbs: 0, totalFats: 0 }
      ]
    }));

    const blankPlan: DietPlan = {
      id: `plan-manual-${Date.now()}`,
      traineeId: selectedTrainee.id,
      traineeName: selectedTrainee.name,
      planName: `نظام ${selectedTrainee.name} الأسبوعي (7 أيام - 5 وجبات)`,
      createdAt: new Date().toISOString().split('T')[0],
      targetMacros: traineeStats.macros,
      actualMacros: { calories: 0, proteinGrams: 0, carbsGrams: 0, fatsGrams: 0, proteinRatio: traineeStats.macros.proteinRatio },
      meals: days[0].meals,
      days,
      supplements: [
        'كرياتين مونوهيدرات: 5 جرام يومياً.',
        'مولتي فيتامين: كبسولة صباحاً مع الإفطار.'
      ],
      hydrationLiters: 4,
      sleepHours: 8,
      coachNotes: 'نظام غذائي أسبوعي مخصص تم تصميمه بواسطة الكابتن.'
    };

    setActivePlan(blankPlan);
    onSavePlan(blankPlan);
  };

  const handleAutoGenerateClick = () => {
    if (!selectedTrainee) return;
    const plan = autoGenerateDietPlan(selectedTrainee, foodDatabase);
    setActivePlan(plan);
    onSavePlan(plan);
  };

  const handleAddFoodToMeal = (mealId: string, foodId: string) => {
    if (!activePlan || !foodId) return;

    const foodRef = foodDatabase.find(f => f.id === foodId);
    if (!foodRef) return;

    const defaultGrams = foodRef.servingSizeGrams || 100;
    const newPortion: FoodPortion = {
      foodId: foodRef.id,
      foodNameAr: foodRef.nameAr,
      foodNameEn: foodRef.nameEn,
      grams: defaultGrams,
      calories: foodRef.calories,
      protein: foodRef.protein,
      carbs: foodRef.carbs,
      fats: foodRef.fats
    };

    updateActiveDayMeals(mealId, (meal) => {
      const updatedItems = [...meal.items, newPortion];
      return recalculateMeal(meal, updatedItems);
    });
  };

  const handleItemGramsChange = (mealId: string, foodId: string, newGrams: number) => {
    if (!activePlan) return;

    updateActiveDayMeals(mealId, (meal) => {
      const updatedItems = meal.items.map(item => {
        if (item.foodId !== foodId) return item;

        const foodRef = foodDatabase.find(f => f.id === foodId);
        const baseServing = foodRef?.servingSizeGrams || 100;
        const mult = newGrams / baseServing;

        return {
          ...item,
          grams: newGrams,
          calories: Math.round((foodRef?.calories || item.calories) * mult),
          protein: Math.round((foodRef?.protein || item.protein) * mult * 10) / 10,
          carbs: Math.round((foodRef?.carbs || item.carbs) * mult * 10) / 10,
          fats: Math.round((foodRef?.fats || item.fats) * mult * 10) / 10
        };
      });

      return recalculateMeal(meal, updatedItems);
    });
  };

  const handleRemoveItem = (mealId: string, itemIndex: number) => {
    if (!activePlan) return;

    updateActiveDayMeals(mealId, (meal) => {
      const updatedItems = meal.items.filter((_, idx) => idx !== itemIndex);
      return recalculateMeal(meal, updatedItems);
    });
  };

  const recalculateMeal = (meal: Meal, updatedItems: FoodPortion[]): Meal => {
    let cal = 0, p = 0, c = 0, f = 0;
    updatedItems.forEach(it => { cal += it.calories; p += it.protein; c += it.carbs; f += it.fats; });
    return {
      ...meal,
      items: updatedItems,
      totalCalories: Math.round(cal),
      totalProtein: Math.round(p * 10) / 10,
      totalCarbs: Math.round(c * 10) / 10,
      totalFats: Math.round(f * 10) / 10
    };
  };

  const updateActiveDayMeals = (mealId: string, updateFn: (meal: Meal) => Meal) => {
    if (!activePlan) return;

    const updatedMeals = currentMeals.map(m => m.id === mealId ? updateFn(m) : m);

    let updatedDays = activePlan.days ? [...activePlan.days] : [];
    if (updatedDays.length > 0) {
      updatedDays[activeDayIndex] = {
        ...updatedDays[activeDayIndex],
        meals: updatedMeals
      };
    }

    let totCal = 0, totP = 0, totC = 0, totF = 0;
    updatedMeals.forEach(m => { totCal += m.totalCalories; totP += m.totalProtein; totC += m.totalCarbs; totF += m.totalFats; });

    const newPlan: DietPlan = {
      ...activePlan,
      days: updatedDays,
      meals: updatedMeals,
      actualMacros: {
        ...activePlan.actualMacros,
        calories: Math.round(totCal),
        proteinGrams: Math.round(totP),
        carbsGrams: Math.round(totC),
        fatsGrams: Math.round(totF)
      }
    };

    setActivePlan(newPlan);
    onSavePlan(newPlan);
  };

  if (!selectedTrainee) {
    return (
      <div className="bg-[#161616] border border-[#2A2A2A] rounded-3xl p-10 sm:p-14 text-center space-y-4 my-8 shadow-2xl relative overflow-hidden max-w-xl mx-auto">
        <div className="w-16 h-16 rounded-3xl bg-[#9CFF00]/10 border border-[#9CFF00]/30 text-[#9CFF00] flex items-center justify-center mx-auto shadow-[0_0_20px_rgba(156,255,0,0.2)]">
          <Sparkles className="w-8 h-8 stroke-[2]" />
        </div>
        <div className="space-y-2">
          <h3 className="text-xl font-black text-white">لا يوجد متدرب محدد لتصميم النظام 🥗</h3>
          <p className="text-xs text-gray-400 leading-relaxed">
            يرجى إضافة متدرب جديد أولاً من القائمة الرئيسية لتبدأ في تصميم نظامه التغذوي وحساب السعرات والماكروز.
          </p>
        </div>
      </div>
    );
  }

  const target = activePlan?.targetMacros || traineeStats?.macros;
  const actual = activePlan?.actualMacros;

  return (
    <div className="space-y-6 pb-28">
      {/* Top Header Bar */}
      <div className="bg-[#161616] border border-[#2A2A2A] rounded-3xl p-5 sm:p-6 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <Calendar className="w-4 h-4 text-[#9CFF00]" />
            <span className="text-xs font-mono text-[#9CFF00] font-bold uppercase tracking-widest">
              7-DAY DIET PLANNER (5 MEALS / DAY)
            </span>
          </div>
          <h1 className="text-xl sm:text-2xl font-black text-white mt-1">
            تصميم الجدول التغذوي الأسبوعي (7 أيام - 5 وجبات)
          </h1>
          <p className="text-xs text-gray-400 mt-0.5">
            صمم وجبات كل يوم بنفسك، أو صمم وجبة السبت وانسخها لباقي الأسبوع بلمسة واحدة!
          </p>
        </div>

        {/* Trainee Selector & Action Buttons */}
        <div className="flex flex-wrap items-center gap-2 w-full sm:w-auto">
          <div className="bg-[#0A0A0A] border border-[#2A2A2A] rounded-2xl px-3 py-1.5 flex items-center gap-2">
            <span className="text-xs text-gray-400 font-bold">المتدرب:</span>
            <select
              value={selectedTraineeId}
              onChange={(e) => onSelectTraineeId(e.target.value)}
              className="bg-transparent text-white font-bold text-xs outline-none cursor-pointer"
            >
              {trainees.map(t => (
                <option key={t.id} value={t.id} className="bg-[#161616]">
                  {t.name} ({t.weight} كجم)
                </option>
              ))}
            </select>
          </div>

          <button
            onClick={handleStartBlankPlan}
            className="bg-[#222222] hover:bg-[#333333] border border-[#333333] text-gray-200 font-bold px-3 py-2 rounded-2xl text-xs flex items-center gap-1.5 transition-all cursor-pointer"
          >
            <Plus className="w-4 h-4 text-[#9CFF00]" />
            <span>نظام فارغ 7 أيام</span>
          </button>

          <button
            onClick={handleAutoGenerateClick}
            className="bg-[#1A1A1A] hover:bg-[#262626] border border-[#9CFF00]/40 text-[#9CFF00] font-bold px-3 py-2 rounded-2xl text-xs flex items-center gap-1.5 transition-all cursor-pointer"
          >
            <RefreshCw className="w-4 h-4 stroke-[2.5]" />
            <span>مسودة 7 أيام</span>
          </button>

          <button
            onClick={onGoToPdf}
            className="bg-[#9CFF00] hover:bg-[#8BE600] text-black font-black px-4 py-2 rounded-2xl text-xs flex items-center gap-1.5 shadow-[0_0_20px_rgba(156,255,0,0.3)] transition-all cursor-pointer"
          >
            <FileText className="w-4 h-4 stroke-[2.5]" />
            <span>معاينة PDF 📄</span>
          </button>
        </div>
      </div>

      {/* Target Macros Bar */}
      {target && actual && (
        <div className="bg-[#161616] border border-[#2A2A2A] rounded-3xl p-5 grid grid-cols-2 md:grid-cols-4 gap-3 sm:gap-4">
          <div className="bg-[#0A0A0A] border border-[#262626] p-3 rounded-2xl text-center">
            <span className="text-xs font-bold text-gray-400 flex items-center justify-center gap-1">
              <Flame className="w-3.5 h-3.5 text-[#9CFF00]" /> السعرات اليومية
            </span>
            <div className="mt-1.5 text-xl font-black text-[#9CFF00]">
              {actual.calories} <span className="text-xs font-normal text-gray-500">/ {target.calories}</span>
            </div>
          </div>

          <div className="bg-[#0A0A0A] border border-[#262626] p-3 rounded-2xl text-center">
            <span className="text-xs font-bold text-gray-400 flex items-center justify-center gap-1">
              <Dumbbell className="w-3.5 h-3.5 text-blue-400" /> البروتين
            </span>
            <div className="mt-1.5 text-xl font-black text-white">
              {actual.proteinGrams}g <span className="text-xs font-normal text-gray-500">/ {target.proteinGrams}g</span>
            </div>
          </div>

          <div className="bg-[#0A0A0A] border border-[#262626] p-3 rounded-2xl text-center">
            <span className="text-xs font-bold text-gray-400 flex items-center justify-center gap-1">
              <Scale className="w-3.5 h-3.5 text-emerald-400" /> النشويات
            </span>
            <div className="mt-1.5 text-xl font-black text-white">
              {actual.carbsGrams}g <span className="text-xs font-normal text-gray-500">/ {target.carbsGrams}g</span>
            </div>
          </div>

          <div className="bg-[#0A0A0A] border border-[#262626] p-3 rounded-2xl text-center">
            <span className="text-xs font-bold text-gray-400 flex items-center justify-center gap-1">
              <Sparkles className="w-3.5 h-3.5 text-amber-400" /> الدهون الصحّية
            </span>
            <div className="mt-1.5 text-xl font-black text-white">
              {actual.fatsGrams}g <span className="text-xs font-normal text-gray-500">/ {target.fatsGrams}g</span>
            </div>
          </div>
        </div>
      )}

      {/* 7-DAY PILL BAR (السبت إلى الجمعة) */}
      <div className="bg-[#161616] border border-[#2A2A2A] rounded-3xl p-4 space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <h3 className="text-sm font-bold text-white flex items-center gap-2">
            <Calendar className="w-4 h-4 text-[#9CFF00]" />
            اختر اليوم للتعديل (7 أيام الأسبوع)
          </h3>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopyCurrentDayToAllDays}
              className="bg-[#222222] hover:bg-[#333333] border border-[#3A3A3A] text-[#9CFF00] font-bold text-xs px-3.5 py-2 rounded-xl flex items-center gap-1.5 transition-all cursor-pointer"
            >
              <Copy className="w-3.5 h-3.5" />
              <span>نسخ وجبات ({daysNames[activeDayIndex].ar}) لكل أيام الأسبوع 📋</span>
            </button>

            {copiedNotification && (
              <span className="text-xs text-[#9CFF00] font-bold flex items-center gap-1">
                <Check className="w-4 h-4" /> تم النسخ!
              </span>
            )}
          </div>
        </div>

        {/* 7 Days Pills */}
        <div className="grid grid-cols-4 sm:grid-cols-7 gap-2">
          {daysNames.map((d, idx) => {
            const isActive = activeDayIndex === idx;
            return (
              <button
                key={d.en}
                onClick={() => setActiveDayIndex(idx)}
                className={`py-2.5 px-2 rounded-2xl text-xs font-bold transition-all text-center cursor-pointer ${
                  isActive
                    ? 'bg-[#9CFF00] text-black font-black shadow-[0_0_15px_rgba(156,255,0,0.3)] scale-105'
                    : 'bg-[#0A0A0A] text-gray-400 hover:text-white border border-[#262626]'
                }`}
              >
                <span className="block">{d.ar}</span>
                <span className={`text-[9px] block font-mono ${isActive ? 'text-black' : 'text-gray-600'}`}>{d.en}</span>
              </button>
            );
          })}
        </div>
      </div>

      {/* 5 Meals List For Selected Day */}
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <h3 className="text-base font-black text-white flex items-center gap-2">
            <Dumbbell className="w-5 h-5 text-[#9CFF00]" />
            وجبات يوم ({daysNames[activeDayIndex].ar}) — (5 وجبات يومياً)
          </h3>

          <span className="text-xs text-[#9CFF00] font-mono font-bold">
            اليوم {activeDayIndex + 1} من 7
          </span>
        </div>

        {currentMeals.map((meal, index) => (
          <div
            key={meal.id}
            className="bg-[#161616] border border-[#2A2A2A] rounded-3xl p-4 sm:p-5 hover:border-[#9CFF00]/40 transition-all"
          >
            {/* Meal Header */}
            <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between pb-3 border-b border-[#262626] gap-2">
              <div className="flex items-center gap-2.5">
                <div className="w-7 h-7 rounded-xl bg-[#9CFF00]/10 text-[#9CFF00] font-black text-xs flex items-center justify-center border border-[#9CFF00]/30 shrink-0">
                  #{index + 1}
                </div>
                <div>
                  <h4 className="text-xs sm:text-sm font-bold text-white flex items-center gap-2">
                    <span>{meal.titleAr}</span>
                  </h4>
                  {meal.timing && (
                    <span className="text-[10px] text-gray-500 font-mono">التوقيت: {meal.timing}</span>
                  )}
                </div>
              </div>

              <div className="font-mono text-[11px] text-[#9CFF00] font-bold bg-[#0A0A0A] px-2.5 py-1 rounded-xl border border-[#2A2A2A] self-start sm:self-auto">
                {meal.totalCalories} kcal | P:{meal.totalProtein}g C:{meal.totalCarbs}g F:{meal.totalFats}g
              </div>
            </div>

            {/* Food Items List */}
            <div className="mt-4 space-y-3">
              {meal.items.map((item, itemIdx) => (
                <div
                  key={`${item.foodId}-${itemIdx}`}
                  className="bg-[#0A0A0A] border border-[#222222] rounded-2xl p-3 flex flex-col gap-2.5"
                >
                  <div className="flex items-start justify-between gap-2">
                    <div className="flex items-center gap-2">
                      <div className="w-1.5 h-6 bg-[#9CFF00] rounded-full shrink-0"></div>
                      <div>
                        <span className="text-xs font-bold text-white block leading-tight">{item.foodNameAr}</span>
                        <span className="text-[10px] text-gray-400 font-mono block">{item.foodNameEn}</span>
                      </div>
                    </div>

                    <button
                      onClick={() => handleRemoveItem(meal.id, itemIdx)}
                      className="p-1 rounded-lg text-gray-500 hover:text-red-400 hover:bg-red-500/10 transition-colors cursor-pointer shrink-0"
                      title="حذف الصنف"
                    >
                      <Trash2 className="w-4 h-4" />
                    </button>
                  </div>

                  <div className="flex items-center justify-between pt-2 border-t border-[#1C1C1C]">
                    <div className="flex items-center gap-1 bg-[#161616] border border-[#333333] px-2.5 py-1 rounded-xl">
                      <input
                        type="number"
                        step="5"
                        min="5"
                        max="1000"
                        value={item.grams}
                        onChange={(e) => handleItemGramsChange(meal.id, item.foodId, Number(e.target.value))}
                        className="w-12 bg-transparent text-center font-black text-xs text-[#9CFF00] outline-none"
                      />
                      <span className="text-[10px] text-gray-400 font-bold">جرام</span>
                    </div>

                    <div className="text-left font-mono">
                      <span className="text-xs font-black text-[#9CFF00] block">{item.calories} kcal</span>
                      <span className="text-[9px] text-gray-400 block">
                        P:{item.protein}g | C:{item.carbs}g | F:{item.fats}g
                      </span>
                    </div>
                  </div>
                </div>
              ))}

              {/* Add Food Select Dropdown */}
              <div className="pt-2">
                <select
                  value={selectedFoodIdToAdd}
                  onChange={(e) => {
                    setSelectedFoodIdToAdd(e.target.value);
                    if (e.target.value) {
                      handleAddFoodToMeal(meal.id, e.target.value);
                      setSelectedFoodIdToAdd('');
                    }
                  }}
                  className="w-full bg-[#0A0A0A] border border-[#2A2A2A] text-gray-300 rounded-xl py-2 px-3 text-xs outline-none focus:border-[#9CFF00] font-bold cursor-pointer"
                >
                  <option value="">+ اختر صنف طعام لإضافته لوجبة ({meal.titleAr})...</option>
                  {foodDatabase.map(f => (
                    <option key={f.id} value={f.id} className="bg-[#161616]">
                      {f.nameAr} ({f.calories} kcal / {f.servingSizeGrams}ج) - P:{f.protein}g C:{f.carbs}g F:{f.fats}g
                    </option>
                  ))}
                </select>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
