import { Trainee, DietPlan, Meal, FoodPortion, AlternativeItem, FoodItem, DaySchedule } from '../types/nutrition';
import { computeTraineeNutritionStats } from './calculator';

export function calculateAlternativeQuantity(
  baseItem: { protein: number; carbs: number; fats: number; calories: number; grams: number },
  targetFood: FoodItem
): AlternativeItem {
  // Determine dominant macro of base item
  let ratio = 1.0;

  if (baseItem.protein > baseItem.carbs && baseItem.protein > baseItem.fats) {
    // Protein heavy (e.g. Chicken vs Beef/Fish)
    ratio = targetFood.protein > 0 ? baseItem.protein / (targetFood.protein / 100) : 100;
  } else if (baseItem.carbs > baseItem.protein && baseItem.carbs > baseItem.fats) {
    // Carb heavy (e.g. Rice vs Sweet Potato/Oats)
    ratio = targetFood.carbs > 0 ? baseItem.carbs / (targetFood.carbs / 100) : 100;
  } else {
    // Fat heavy (e.g. Olive oil vs Peanut butter)
    ratio = targetFood.fats > 0 ? baseItem.fats / (targetFood.fats / 100) : 100;
  }

  const targetGrams = Math.round(Math.max(10, ratio));
  const mult = targetGrams / targetFood.servingSizeGrams;

  return {
    foodId: targetFood.id,
    foodNameAr: targetFood.nameAr,
    foodNameEn: targetFood.nameEn,
    grams: targetGrams,
    calories: Math.round(targetFood.calories * mult),
    protein: Math.round(targetFood.protein * mult * 10) / 10,
    carbs: Math.round(targetFood.carbs * mult * 10) / 10,
    fats: Math.round(targetFood.fats * mult * 10) / 10
  };
}

export function autoGenerateDietPlan(
  trainee: Trainee,
  foodDatabase: FoodItem[],
  customPlanName?: string
): DietPlan {
  const { targetCalories, macros } = computeTraineeNutritionStats(trainee);

  // Meal breakdown percentages:
  // Breakfast: 20%
  // Lunch: 30%
  // Pre-Workout: 12%
  // Post-Workout: 18%
  // Dinner: 20%

  const findFood = (id: string): FoodItem => {
    return foodDatabase.find(f => f.id === id) || foodDatabase[0];
  };

  // 1. Breakfast (Oats + Egg Whites + Whole Egg)
  const bOats = findFood('f11'); // Oats
  const bWhites = findFood('f6'); // Egg Whites
  const bEgg = findFood('f7'); // Whole Egg
  const bToast = findFood('f15'); // Toast alt

  const oatsGrams = Math.round((macros.carbsGrams * 0.20) / (bOats.carbs / 100));
  const whitesGrams = Math.round((macros.proteinGrams * 0.15) / (bWhites.protein / 100));

  const meal1Items: FoodPortion[] = [
    {
      foodId: bOats.id,
      foodNameAr: bOats.nameAr,
      foodNameEn: bOats.nameEn,
      grams: oatsGrams,
      calories: Math.round(bOats.calories * (oatsGrams / 100)),
      protein: Math.round(bOats.protein * (oatsGrams / 100) * 10) / 10,
      carbs: Math.round(bOats.carbs * (oatsGrams / 100) * 10) / 10,
      fats: Math.round(bOats.fats * (oatsGrams / 100) * 10) / 10,
      alternatives: [calculateAlternativeQuantity({ protein: bOats.protein * (oatsGrams/100), carbs: bOats.carbs * (oatsGrams/100), fats: bOats.fats * (oatsGrams/100), calories: bOats.calories * (oatsGrams/100), grams: oatsGrams }, bToast)]
    },
    {
      foodId: bWhites.id,
      foodNameAr: bWhites.nameAr,
      foodNameEn: bWhites.nameEn,
      grams: whitesGrams,
      calories: Math.round(bWhites.calories * (whitesGrams / 100)),
      protein: Math.round(bWhites.protein * (whitesGrams / 100) * 10) / 10,
      carbs: Math.round(bWhites.carbs * (whitesGrams / 100) * 10) / 10,
      fats: Math.round(bWhites.fats * (whitesGrams / 100) * 10) / 10
    },
    {
      foodId: bEgg.id,
      foodNameAr: bEgg.nameAr,
      foodNameEn: bEgg.nameEn,
      grams: 50,
      calories: 77,
      protein: 6.5,
      carbs: 0.5,
      fats: 5.5
    }
  ];

  // 2. Lunch (Chicken Breast + Basmati Rice + Salad)
  const lChicken = findFood('f1');
  const lBeef = findFood('f2');
  const lRice = findFood('f10');
  const lSweetPotato = findFood('f12');
  const lSalad = findFood('f27');

  const chickenGrams = Math.round((macros.proteinGrams * 0.35) / (lChicken.protein / 100));
  const riceGrams = Math.round((macros.carbsGrams * 0.35) / (lRice.carbs / 100));

  const meal2Items: FoodPortion[] = [
    {
      foodId: lChicken.id,
      foodNameAr: lChicken.nameAr,
      foodNameEn: lChicken.nameEn,
      grams: chickenGrams,
      calories: Math.round(lChicken.calories * (chickenGrams / 100)),
      protein: Math.round(lChicken.protein * (chickenGrams / 100) * 10) / 10,
      carbs: Math.round(lChicken.carbs * (chickenGrams / 100) * 10) / 10,
      fats: Math.round(lChicken.fats * (chickenGrams / 100) * 10) / 10,
      alternatives: [calculateAlternativeQuantity({ protein: lChicken.protein * (chickenGrams/100), carbs: 0, fats: 3.6, calories: 165, grams: chickenGrams }, lBeef)]
    },
    {
      foodId: lRice.id,
      foodNameAr: lRice.nameAr,
      foodNameEn: lRice.nameEn,
      grams: riceGrams,
      calories: Math.round(lRice.calories * (riceGrams / 100)),
      protein: Math.round(lRice.protein * (riceGrams / 100) * 10) / 10,
      carbs: Math.round(lRice.carbs * (riceGrams / 100) * 10) / 10,
      fats: Math.round(lRice.fats * (riceGrams / 100) * 10) / 10,
      alternatives: [calculateAlternativeQuantity({ protein: 2.7, carbs: lRice.carbs * (riceGrams/100), fats: 0.3, calories: 130, grams: riceGrams }, lSweetPotato)]
    },
    {
      foodId: lSalad.id,
      foodNameAr: lSalad.nameAr,
      foodNameEn: lSalad.nameEn,
      grams: 150,
      calories: 25,
      protein: 1,
      carbs: 5,
      fats: 0.2
    }
  ];

  // 3. Pre-Workout (Banana + Peanut Butter)
  const pBanana = findFood('f23');
  const pPb = findFood('f18');

  const meal3Items: FoodPortion[] = [
    {
      foodId: pBanana.id,
      foodNameAr: pBanana.nameAr,
      foodNameEn: pBanana.nameEn,
      grams: 120,
      calories: 107,
      protein: 1.3,
      carbs: 27.6,
      fats: 0.4
    },
    {
      foodId: pPb.id,
      foodNameAr: pPb.nameAr,
      foodNameEn: pPb.nameEn,
      grams: 20,
      calories: 118,
      protein: 5,
      carbs: 4,
      fats: 10
    }
  ];

  // 4. Post-Workout (Whey + Banana)
  const pWhey = findFood('f8');

  const meal4Items: FoodPortion[] = [
    {
      foodId: pWhey.id,
      foodNameAr: pWhey.nameAr,
      foodNameEn: pWhey.nameEn,
      grams: 30,
      calories: 120,
      protein: 25,
      carbs: 1,
      fats: 1
    },
    {
      foodId: pBanana.id,
      foodNameAr: pBanana.nameAr,
      foodNameEn: pBanana.nameEn,
      grams: 100,
      calories: 89,
      protein: 1.1,
      carbs: 23,
      fats: 0.3
    }
  ];

  // 5. Dinner (Cottage Cheese + Olive Oil + Salad)
  const dCheese = findFood('f5'); // Cottage Cheese
  const dOliveOil = findFood('f19');
  const dYogurt = findFood('f28');

  const cheeseGrams = Math.round((macros.proteinGrams * 0.20) / (dCheese.protein / 100));

  const meal5Items: FoodPortion[] = [
    {
      foodId: dCheese.id,
      foodNameAr: dCheese.nameAr,
      foodNameEn: dCheese.nameEn,
      grams: cheeseGrams,
      calories: Math.round(dCheese.calories * (cheeseGrams / 100)),
      protein: Math.round(dCheese.protein * (cheeseGrams / 100) * 10) / 10,
      carbs: Math.round(dCheese.carbs * (cheeseGrams / 100) * 10) / 10,
      fats: Math.round(dCheese.fats * (cheeseGrams / 100) * 10) / 10,
      alternatives: [calculateAlternativeQuantity({ protein: dCheese.protein * (cheeseGrams/100), carbs: 3, fats: 4, calories: 98, grams: cheeseGrams }, dYogurt)]
    },
    {
      foodId: dOliveOil.id,
      foodNameAr: dOliveOil.nameAr,
      foodNameEn: dOliveOil.nameEn,
      grams: 10,
      calories: 88,
      protein: 0,
      carbs: 0,
      fats: 10
    },
    {
      foodId: lSalad.id,
      foodNameAr: lSalad.nameAr,
      foodNameEn: lSalad.nameEn,
      grams: 150,
      calories: 25,
      protein: 1,
      carbs: 5,
      fats: 0.2
    }
  ];

  const buildMeal = (id: string, type: any, titleAr: string, titleEn: string, items: FoodPortion[], notes?: string, timing?: string): Meal => {
    let cal = 0, p = 0, c = 0, f = 0;
    items.forEach(it => {
      cal += it.calories;
      p += it.protein;
      c += it.carbs;
      f += it.fats;
    });
    return {
      id,
      type,
      titleAr,
      titleEn,
      timing,
      items,
      notes,
      totalCalories: Math.round(cal),
      totalProtein: Math.round(p * 10) / 10,
      totalCarbs: Math.round(c * 10) / 10,
      totalFats: Math.round(f * 10) / 10
    };
  };

  const daysNames = [
    { ar: 'السبت', en: 'Saturday' },
    { ar: 'الأحد', en: 'Sunday' },
    { ar: 'الإثنين', en: 'Monday' },
    { ar: 'الثلاثاء', en: 'Tuesday' },
    { ar: 'الأربعاء', en: 'Wednesday' },
    { ar: 'الخميس', en: 'Thursday' },
    { ar: 'الجمعة', en: 'Friday' }
  ];

  const default5Meals: Meal[] = [
    buildMeal('m1', 'breakfast', '1. وجبة الإفطار', 'Breakfast', meal1Items, 'يمكن تناول الشوفان مع القرفة وسكر دايت.', '08:30 AM'),
    buildMeal('m2', 'snack_1', '2. وجبة سناك صباحي', 'Morning Snack', meal3Items, 'تفاحة أو ثمرة فواكه مع المكسرات.', '11:30 AM'),
    buildMeal('m3', 'lunch', '3. وجبة الغداء الرئيسية', 'Lunch', meal2Items, 'وزن اللحوم والأرز بعد الطبخ.', '02:30 PM'),
    buildMeal('m4', 'post_workout', '4. وجبة قبل/بعد التمرين', 'Workout Meal', meal4Items, 'بعد التمرين مباشرة.', '06:30 PM'),
    buildMeal('m5', 'dinner', '5. وجبة العشاء', 'Dinner', meal5Items, 'وجبة غنية بكازين البروتين لبناء العضلات طوال النوم.', '10:00 PM')
  ];

  const days: DaySchedule[] = daysNames.map((d, idx) => ({
    dayIndex: idx,
    dayNameAr: d.ar,
    dayNameEn: d.en,
    meals: default5Meals.map(m => ({ ...m, id: `m-${idx}-${m.id}` }))
  }));

  let actualCal = 0, actualP = 0, actualC = 0, actualF = 0;
  default5Meals.forEach(m => {
    actualCal += m.totalCalories;
    actualP += m.totalProtein;
    actualC += m.totalCarbs;
    actualF += m.totalFats;
  });

  return {
    id: `plan-${Date.now()}`,
    traineeId: trainee.id,
    traineeName: trainee.name,
    planName: `نظام ${trainee.name} التغذوي الأسبوعي (7 أيام - 5 وجبات يومياً)`,
    createdAt: new Date().toISOString().split('T')[0],
    targetMacros: macros,
    actualMacros: {
      calories: Math.round(actualCal),
      proteinGrams: Math.round(actualP),
      carbsGrams: Math.round(actualC),
      fatsGrams: Math.round(actualF),
      proteinRatio: macros.proteinRatio
    },
    meals: default5Meals,
    days,
    supplements: [
      'كرياتين مونوهيدرات: 5 جرام يومياً بعد التمرين.',
      'مولتي فيتامين: كبسولة واحدة صباحاً مع الإفطار.',
      'أوميجا 3: 1000 ملجم مع الغداء.'
    ],
    hydrationLiters: 4,
    sleepHours: 8,
    coachNotes: 'نظام غذائي أسبوعي متكامل 7 أيام (5 وجبات يومياً). التزم بالتفاصيل للحصول على أفضل نتيجة.'
  };
}
